### PR TITLE
fix readme

### PR DESCRIPTION
**Pull request by feross**

### CODE REVIEW

**Comment by feross** [comment]
Also, can you do a release so I can use the web crypto changes?

Thanks for all the fast merges! You da bomb :+1:

**Comment by michaelrhodes** [comment]
Yeah, no problem, I was just holding out until the test badges were in the readme.

**Comment by michaelrhodes** [comment]
I'll fix the readme properly later; I'm kind of at work at the moment :p

**Comment by michaelrhodes** [comment]
[Published](https://www.npmjs.com/package/simple-sha1)

**Comment by feross** [comment]
Thanks!

**Pull request merged**
